[project]
name = "pyml-book"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gdown>=5.2.1",
    "hyperopt>=0.2.7",
    "ipywidgets>=8.1.8",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "mlxtend>=0.24.0",
    "nltk>=3.9.3",
    "numpy>=2.4.2",
    "pandas>=3.0.1",
    "pip>=26.0.1",
    "portalocker>=2.0.0",
    "pyprind>=2.11.3",
    "pytorch-lightning>=2.6.1",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
    "setuptools>=80.0.0,<81.0.0",
    "skimpy>=0.0.20",
    "tensorboard>=2.20.0",
    "torch==2.3.0",
    "torchdata==0.8.0",
    "torchtext==0.18.0",
    "torchvision==0.18.0",
    "tqdm>=4.67.3",
    "xgboost>=3.2.0",
]
